version: 2

sphinx:
  configuration: docs/read_the_docs/source/conf.py

build:
<<<<<<< HEAD
  os: ubuntu-22.04
  tools:
    python: "3.8"
=======
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/read_the_docs/requirements.txt
>>>>>>> ba65875... RTD and bsb version fixes. [ci skip]
