version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.9.0
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run:
          name: Apply rubocop
          command: |
            rubocop --format simple --only Layout --debug
      - run: 
          name: Run tests
          command: |
            mkdir BuildResidentialHPXML
            mv hpxml_schemas BuildResidentialHPXML
            mv resources BuildResidentialHPXML
            mv tests BuildResidentialHPXML
            mv measure* BuildResidentialHPXML
            cd BuildResidentialHPXML
            ruby tests/build_residential_hpxml_test.rb