# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.1.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run all integrity checks
        run: |
          rake test:integrity_checks

      - name: Run all unit tests
        run: |
          rake test:unit_tests

      - name: Run measures osw test
        run: |
          rake test:measures_osw

      - name: Run all regression tests
        run: |
          rake test:regression_tests

      - name: Store example osws
        uses: actions/upload-artifact@v2
        with:
          path: workflows/results/results.csv
          name: example_osws.csv          

      - name: Store measures osws
        uses: actions/upload-artifact@v2
        with:
          path: test/test_measures_osw/results/results.csv
          name: measures_osws.csv

      - name: Store buildstock csv
        uses: actions/upload-artifact@v2
        with:
          path: test/test_measures_osw/buildstock.csv
          name: buildstock.csv

  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.8.4]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
