name: ci
on: [pull_request]
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]'))"
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run integrity checks for all projects
        run: |
          rake unit_tests:project_integrity_checks

      - name: Run all integrity check unit tests
        run: |
          rake unit_tests:integrity_check_tests

      - name: Run all measure tests
        run: |
          rake unit_tests:measure_tests

  integration-tests:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for Testing')
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run integration tests for sampled datapoints
        run: |
          rake integration:workflow_tests

      - name: Upload integration results
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/test_samples_osw/baseline
            test/test_samples_osw/upgrades
          name: samples

  regression-tests:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for Testing')
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run regression tests for all example osws
        run: |
          rake regression:workflow_tests

      - name: Upload regression results
        uses: actions/upload-artifact@v2
        with:
          path: |
            workflows/results
          name: examples 

  tests-results:
    runs-on: ubuntu-latest
    needs: [integration-tests, regression-tests]
    steps:
      - name: Checkout for PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Checkout the PR branch instead of the merge commit

      - name: Checkout for push
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Setup git branch and python deps
        shell: bash
        run: |
          branch_name=""
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            branch_name="${{ github.head_ref }}"
            echo "Checking out branch: $branch_name"
            git checkout -b $branch_name || git checkout $branch_name
          fi

          pip install numpy
          pip install pandas
          pip install seaborn
          pip install matplotlib
          pip install plotly
          pip install kaleido

      - name: Download integration results
        uses: actions/download-artifact@v2
        with:
          path: |
            samples
          name: samples

      - name: Make integration comparisons
        shell: bash
        run: |
          cp samples/baseline/results/results.csv test/test_samples_osw/results/project_national_feature.csv
          python test/res_results_csv_comparisons.py test/test_samples_osw/results/project_national_develop.csv test/test_samples_osw/results/project_national_feature.csv

      - name: Download regression results
        uses: actions/download-artifact@v2
        with:
          path: |
            examples
          name: examples

      - name: Make regression comparisons
        shell: bash
        run: |
          cp examples/feature.csv workflows/results/feature.csv
          python test/res_results_csv_comparisons.py workflows/results/develop.csv workflows/results/feature.csv

      - name: Commit latest results and comparisons
        shell: bash        
        run: |
          git status
          git add test/test_samples_osw/results/project_national_feature.csv
          git add test/test_samples_osw/results/comparisons
          git add workflows/results/feature.csv
          git add workflows/results/comparisons

          git status
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Figure comparisons."
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              branch_name="${{ github.head_ref }}"
              echo "Pushing to branch: $branch_name"
              git push -u origin $branch_name
            else
              git push
            fi
          fi

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
