name: ci

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ synchronize, opened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.2.0
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Show environment
        run: |
          bundle -v
          ruby -v

      - name: Run integrity checks for all projects
        run: |
          rake unit_tests:project_integrity_checks

      - name: Run all integrity check unit tests
        run: |
          rake unit_tests:integrity_check_tests

      - name: Run all measure tests
        run: |
          rake unit_tests:measure_tests

      - name: Run regression tests for all example osws
        run: |
          rake regression:workflow_tests

      - name: Run integration tests for sampled datapoints
        run: |
          rake integration:workflow_tests

      - name: Upload regression results
        uses: actions/upload-artifact@v2
        with:
          path: |
            workflows/results
          name: examples

      - name: Upload integration results
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/test_samples_osw/baseline/project_national/results
          name: results

  compare-results:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Store base integration results
        uses: actions/upload-artifact@v2
        with:
          path: test/test_measures_osw/base_results
          name: base_results

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download base results
        uses: actions/download-artifact@v2
        with:
          path: |
            base_results
          name: base_results

      - name: Download feature results
        uses: actions/download-artifact@v2
        with:
          path: |
            results
          name: results

      - name: Compare results
        run: |
          cp -r base_results/results*.csv test/test_samples_osw/base_results
          mkdir test/test_samples_osw/results
          cp -r results/results* test/test_samples_osw/results
          ruby test/compare.rb

      - name: Store comparisons
        uses: actions/upload-artifact@v2
        with:
          path: test/test_samples_osw/comparisons
          name: comparisons

  update-results:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download feature results
        uses: actions/download-artifact@v2
        with:
          path: |
            results
          name: results

      - name: Commit latest results
        shell: bash        
        run: |
          branch_name="${{ github.head_ref }}"
          git pull origin $branch_name
          cp -r results/results* test/test_samples_osw/base_results
          git add test/test_samples_osw/base_results
          git status
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Latest results."
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name
          fi

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
