name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install
      - name: Run integrity checks for all projects
        run: |
          rake unit_tests:project_integrity_checks
      - name: Run all integrity check unit tests
        run: |
          rake unit_tests:integrity_check_tests
      - name: Run all measure tests
        run: |
          rake unit_tests:measure_tests

  integration:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Run integration tests for sampled datapoints
        run: |
          rake integration:workflow_tests
      - name: Store workflow results
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/test_samples_osw/baseline
            test/test_samples_osw/upgrades
          name: samples

  regression:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Run regression tests for all example osws
        run: |
          rake regression:workflow_tests
      - name: Store workflow results
        uses: actions/upload-artifact@v2
        with:
          path: workflows/results
          name: examples 

  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [integration, regression]
    strategy:
      matrix:
        python-version: [3.8.4]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
