name: ci

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ synchronize, opened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:2.9.0
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Update all measures
        run: |
          rake update_measures

      - name: Regenerate test osms
        run: |
          rake test:regenerate_osms

      - name: Run all unit tests
        run: |
          rake test:unit_tests

      - name: Run all regression tests
        run: |
          rake test:regression_tests

      - name: Store example osws
        uses: actions/upload-artifact@v2
        with:
          path: workflows/results
          name: example_osws

      - name: Store measures osws
        uses: actions/upload-artifact@v2
        with:
          path: test/test_measures_osw/project_national_results
          name: results

      - name: Store schedules
        uses: actions/upload-artifact@v2
        with:
          path: resources/measures/ResidentialScheduleGenerator/tests/output/test_sweep_building_ids_and_num_occupants
          name: schedules

  compare-results:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - name: Store base measures osws
        uses: actions/upload-artifact@v2
        with:
          path: test/test_measures_osw/base_results
          name: base_results

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download base results
        uses: actions/download-artifact@v2
        with:
          path: |
            base_results
          name: base_results

      - name: Download feature results
        uses: actions/download-artifact@v2
        with:
          path: |
            results
          name: results

      - name: Compare results
        run: |
          cp -r base_results/results*.csv test/test_measures_osw/base_results
          mkdir test/test_measures_osw/results
          cp -r results/results* test/test_measures_osw/results
          ruby test/compare.rb

      - name: Store comparisons
        uses: actions/upload-artifact@v2
        with:
          path: test/test_measures_osw/comparisons
          name: comparisons

  update-results:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Download feature results
        uses: actions/download-artifact@v2
        with:
          path: |
            results
          name: results

      - name: Commit latest results
        shell: bash        
        run: |
          branch_name="${{ github.head_ref }}"
          git pull origin $branch_name
          cp -r results/results* test/test_measures_osw/base_results
          git add test/test_measures_osw/base_results
          git status
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Latest results."
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name
          fi

  docs:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.8.4]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build documentation
        run: |
          cd docs/read_the_docs
          pip install -r requirements.txt
          make html

      - name: Store docs
        uses: actions/upload-artifact@v2
        with:
          path: docs/read_the_docs/build
          name: readthedocs
