name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install
      - name: Run integrity checks for all projects
        run: |
          rake unit_tests:project_integrity_checks
      - name: Run all integrity check unit tests
        run: |
          rake unit_tests:integrity_check_tests
      - name: Run all measure tests
        run: |
          rake unit_tests:measure_tests

  integration:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install
      - name: Run integration tests for sampled datapoints
        run: |
          rake integration:workflow_tests
      - name: Store workflow results
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/test_samples_osw/baseline
            test/test_samples_osw/upgrades
          name: samples

      - name: Make comparison figures
        shell: python
        run: |
          python test/res_results_csv_comparison.py

      - name: Store comparison figures
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/results/figures
          name: figures

      - name: Commit comparison figures
        if: contains(github.event.pull_request.labels.*.name, 'Ready for Comparison')
        run: |
          git add test/results/figures
          git commit -m "Figure comparisons."
          git push

  regression:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install
      - name: Run regression tests for all example osws
        run: |
          rake regression:workflow_tests
      - name: Store workflow results
        uses: actions/upload-artifact@v2
        with:
          path: workflows/results
          name: examples 

  docs:
    runs-on: ubuntu-latest
    needs: [integration, regression]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
