name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ synchronize, opened ]
  workflow_dispatch:

jobs:
  clean-files:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Clean Files
        shell: bash
        run: |
          sed -i -e 's/[[:space:]]*$//' resources/options_lookup.tsv # Remove whitespace
          (sed -u 1q ; sort -k1 -k2) < resources/options_lookup.tsv > sorted_options_lookup.tsv
          mv sorted_options_lookup.tsv resources/options_lookup.tsv # Sort on first two columns

      - name: Upload formatted options_lookup 
        uses: actions/upload-artifact@v3
        with:
          path: resources/options_lookup.tsv
          name: options_lookup

  update-results-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Download formatted options_lookup samples
        uses: actions/download-artifact@v3
        with:
          path: resources
          name: options_lookup

      - name: Commit latest results
        shell: bash        
        run: |
          branch_name="${{ github.head_ref }}"
          git pull origin $branch_name
          git add resources/options_lookup.tsv
          git status
          if [[ $(git diff --cached --exit-code) ]]; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Latest results."
            echo "Pushing to branch: $branch_name"
            git push -u origin $branch_name
          fi
