name: ci
on: [pull_request]
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]'))"
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run integrity checks for all projects
        run: |
          #rake unit_tests:project_integrity_checks

      - name: Run all integrity check unit tests
        run: |
          rake unit_tests:integrity_check_tests

      - name: Run all measure tests
        run: |
          rake unit_tests:measure_tests

  integration-tests:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for Testing')
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run integration tests for sampled datapoints
        run: |
          rake integration:workflow_tests

      - name: Upload integration results
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/test_samples_osw/baseline
            test/test_samples_osw/upgrades
          name: samples

  integration-results:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'

      - name: Download integration results
        uses: actions/download-artifact@v2
        with:
          path: |
            samples
          name: samples

      - name: Make comparison figures
        shell: bash
        run: |
          cp samples/baseline/results/results.csv test/results/project_testing_develop.csv
          cp samples/baseline/results/results.csv test/results/project_testing_feature.csv
          pip install numpy
          pip install pandas
          pip install seaborn
          pip install matplotlib
          python test/res_results_csv_comparisons.py

      - name: Upload comparison figures
        uses: actions/upload-artifact@v2
        with:
          path: |
            test/results/figures
          name: figures

      - name: Commit comparison figures
        shell: bash        
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add test/results/project_testing_develop.csv
          git add test/results/project_testing_feature.csv
          git add test/results/figures
          git commit -m "Figure comparisons."
          git push

  regression-tests:
    if: contains(github.event.pull_request.labels.*.name, 'Ready for Testing')
    runs-on: ubuntu-latest
    needs: build
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run regression tests for all example osws
        run: |
          rake regression:workflow_tests

      - name: Upload regression results
        uses: actions/upload-artifact@v2
        with:
          path: |
            workflows/results
          name: examples 

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
